Repository knative/build, pull requests merged in 2018-11, with the labels that each got.

#454 More updates to the release script
  Gopkg.lock
  hack/release.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/dummy.go
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#453 Add optional tags for build spec
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/builder/cluster/builder.go
  pkg/builder/nop/builder.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
Labels: approved, lgtm, size/M

#451 Multiple Input sources
  cmd/git-init/main.go
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/build_validation.go
  pkg/apis/build/v1alpha1/build_validation_test.go
  pkg/apis/build/v1alpha1/target_path_validation.go
  pkg/apis/build/v1alpha1/target_path_validation_test.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/builder/cluster/convert/convert.go
  pkg/builder/cluster/convert/convert_test.go
  pkg/builder/cluster/convert/testdata/custom-git-sources.yaml
  pkg/builder/cluster/convert/testdata/custom-sources.yaml
  pkg/builder/cluster/convert/testdata/gcs-archive-sources.yaml
  pkg/builder/cluster/convert/testdata/git-sources.yaml
  test/e2e/invalid_test.go
  test/e2e/simple_test.go
  test/gcs-archive/2-build.yaml
  test/reuse-git-init/test.yaml
  test/sources/test.yaml
  test/sources/test2.yaml
  test/sources/test3.yaml
Labels: approved, lgtm, size/XXL

#457 Move pkg/builder/cluster/convert to pkg/reconciler/build/resources
  pkg/builder/cluster/builder.go
  pkg/builder/cluster/convert/testdata/custom-git-sources.yaml
  pkg/builder/cluster/convert/testdata/custom-source.yaml
  pkg/builder/cluster/convert/testdata/custom-sources.yaml
  pkg/builder/cluster/convert/testdata/env-valuefrom.yaml
  pkg/builder/cluster/convert/testdata/env.yaml
  pkg/builder/cluster/convert/testdata/gcs-archive-sources.yaml
  pkg/builder/cluster/convert/testdata/gcs-archive.yaml
  pkg/builder/cluster/convert/testdata/gcs-manifest.yaml
  pkg/builder/cluster/convert/testdata/git-revision.yaml
  pkg/builder/cluster/convert/testdata/git-sources.yaml
  pkg/builder/cluster/convert/testdata/git-subpath.yaml
  pkg/builder/cluster/convert/testdata/helloworld.yaml
  pkg/builder/cluster/convert/testdata/nodeselector.yaml
  pkg/builder/cluster/convert/testdata/resources.yaml
  pkg/builder/cluster/convert/testdata/security-context.yaml
  pkg/builder/cluster/convert/testdata/two-step.yaml
  pkg/builder/cluster/convert/testdata/volumes.yaml
  pkg/builder/cluster/convert/testdata/workingdir.yaml
  pkg/builder/cluster/convert/testdata/workspace.yaml
  pkg/builder/validation/error.go
  pkg/reconciler/build/resources/pod.go
  pkg/reconciler/build/resources/pod_test.go
Labels: approved, lgtm, size/XL

#460 Add omitempty to StepsCompleted…
  pkg/apis/build/v1alpha1/build_types.go
Labels: approved, lgtm, size/XS

#463 Add e2e test for sources with targetpath
  test/sources/test-gopath.yaml
Labels: approved, lgtm, size/M

#465 Add GitHub Commit ID to logs as label
  Gopkg.lock
  Gopkg.toml
  cmd/controller/kodata/HEAD
  cmd/creds-init/kodata/HEAD
  cmd/git-init/kodata/HEAD
  cmd/logs/kodata/HEAD
  cmd/nop/kodata/HEAD
  cmd/webhook/kodata/HEAD
  third_party/VENDOR-LICENSE
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/knative/pkg/apis/duck/patch.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/retired_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/sinkable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/duck/verify.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/apis/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/changeset/commit.go
  vendor/github.com/knative/pkg/changeset/doc.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/controller/helper.go
  vendor/github.com/knative/pkg/kmeta/accessor.go
  vendor/github.com/knative/pkg/logging/config.go
  vendor/github.com/knative/pkg/logging/logkey/constants.go
  vendor/github.com/knative/pkg/test/e2e_flags.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
  vendor/github.com/knative/pkg/webhook/certs.go
  vendor/go.opencensus.io/plugin/ochttp/client.go
  vendor/go.opencensus.io/plugin/ochttp/client_stats.go
  vendor/go.opencensus.io/plugin/ochttp/doc.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/b3/b3.go
  vendor/go.opencensus.io/plugin/ochttp/server.go
  vendor/go.opencensus.io/plugin/ochttp/span_annotator.go
  vendor/go.opencensus.io/plugin/ochttp/stats.go
  vendor/go.opencensus.io/plugin/ochttp/trace.go
  vendor/go.opencensus.io/trace/propagation/propagation.go
Labels: approved, lgtm, size/XXL

#466 Add bash helper function to get pod logs
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#467 Delete unused testdata directory, useless test, unused test methods
  Gopkg.lock
  pkg/apis/build/v1alpha1/build_types_test.go
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/README.md
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/bazel/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/docker/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/dotnet/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/dotnet/examples/TestApp-2.0/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/dotnet/examples/TestApp/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/gcloud/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/git/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/go/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/go/examples/hello_world/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/go/examples/hello_world_app/app.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/go/examples/hello_world_app/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/go/examples/https_test/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/go/examples/import_workspace/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/go/examples/whole_workspace/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/golang-project/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/golang-project/examples/custom_base/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/golang-project/examples/hello_world/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/golang-project/examples/hello_world_migrated/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/golang-project/examples/multi_bin/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/golang-project/examples/static_webserver/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/gradle/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/gradle/examples/spring_boot/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/gsutil/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/gsutil/examples/gcs_push/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/javac/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/kubectl/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/kubectl/examples/pods-list/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/mvn/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/mvn/examples/spring_boot/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/npm/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/npm/examples/hello_world/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/wget/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/yarn/cloudbuild.yaml
  pkg/apis/build/v1alpha1/testdata/cloudbuilders/yarn/examples/hello_world/cloudbuild.yaml
  pkg/buildtest/data.go
  pkg/buildtest/json.go
  pkg/buildtest/yaml.go
  vendor/github.com/go-yaml/yaml/LICENSE
  vendor/github.com/go-yaml/yaml/LICENSE.libyaml
  vendor/github.com/go-yaml/yaml/apic.go
  vendor/github.com/go-yaml/yaml/decode.go
  vendor/github.com/go-yaml/yaml/emitterc.go
  vendor/github.com/go-yaml/yaml/encode.go
  vendor/github.com/go-yaml/yaml/parserc.go
  vendor/github.com/go-yaml/yaml/readerc.go
  vendor/github.com/go-yaml/yaml/resolve.go
  vendor/github.com/go-yaml/yaml/scannerc.go
  vendor/github.com/go-yaml/yaml/sorter.go
  vendor/github.com/go-yaml/yaml/writerc.go
  vendor/github.com/go-yaml/yaml/yaml.go
  vendor/github.com/go-yaml/yaml/yamlh.go
  vendor/github.com/go-yaml/yaml/yamlprivateh.go
Labels: approved, lgtm, size/XXL

#472 Increase timeout for TestSimpleBuild
  test/e2e/simple_test.go
Labels: approved, lgtm, size/XS

#473 Fix logger name
  cmd/creds-init/main.go
Labels: approved, lgtm, size/XS

#476 Fix swapped reason/message when pod is initializing
  pkg/builder/cluster/builder.go
  pkg/builder/cluster/builder_test.go
Labels: approved, lgtm, size/XS

#475 Run gofmt
  pkg/apis/build/v1alpha1/metadata_validation_test.go
  pkg/reconciler/build/build_test.go
  test/e2e/simple_test.go
Labels: approved, lgtm, size/S

#464 Remove builder interface, linearize pod creation and watching
  .gitignore
  Gopkg.lock
  cmd/controller/main.go
  pkg/builder/cluster/builder.go
  pkg/builder/cluster/builder_test.go
  pkg/builder/interface.go
  pkg/builder/nop/builder.go
  pkg/builder/nop/builder_test.go
  pkg/buildtest/wait.go
  pkg/controller/controller.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/build/resources/pod.go
  pkg/reconciler/build/resources/pod_test.go
  pkg/reconciler/build/validate_build.go
  pkg/reconciler/build/validation_test.go
  test/build-with-timeout/build-with-low-timeout.yaml
  test/e2e/e2e.go
  test/e2e/simple_test.go
Labels: approved, lgtm, size/XXL

#477 Follow up with more aggressive collapse.
  test/e2e/simple_test.go
Labels: approved, lgtm, size/S

#478 Fix spelling errors
  pkg/apis/build/v1alpha1/build_validation_test.go
  pkg/apis/build/v1alpha1/target_path_validation_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#480 Populate status in case of validation errors 👷
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
Labels: approved, lgtm, size/S

#481 Add missing serviceaccount & secrets tests for BuildStatus validation 🚡
  pkg/reconciler/build/build_test.go
Labels: approved, lgtm, size/L
