Repository knative/build, pull requests merged in 2018-08, with the labels that each got.

#293 Apply template args to step image
  pkg/builder/common.go
  pkg/builder/common_test.go
  test/template-args/0-template.yaml
Labels: approved, lgtm, size/M

#294 Show additional build state info in CLI
  config/300-build.yaml
  config/300-buildtemplate.yaml
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/builder/cluster/builder.go
Labels: approved, lgtm, size/M

#298 Use new valid deploy key, delete old key
  test/git-ssh/0-secret.yaml
  test/git-ssh/id_rsa
  test/git-ssh/id_rsa.pub
Labels: approved, lgtm, size/M

#299 Minor quality of life improvements
  pkg/builder/cluster/convert/convert.go
Labels: approved, lgtm, size/XS

#300 Correct minor typo
  pkg/controller/build/controller_test.go
Labels: approved, lgtm, size/XS

#307 Make e2e-tests.sh portable
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#308 Also make presubmit-tests.sh portable
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#309 Show intermediate update of build steps
  pkg/builder/cluster/builder.go
  pkg/builder/cluster/builder_test.go
  test/multiple-steps/build-with-more-steps.yaml
Labels: approved, lgtm, size/M

#311 Vendor the test-infra scripts
  Gopkg.lock
  Gopkg.toml
  hack/release.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XL

#314 Make verify-codegen.sh compatible with OS X
  hack/verify-codegen.sh
Labels: approved, lgtm, size/XS

#316 add cleanup step for clusterbuildtemplates in doc
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#317 Dockerfile for new minimal base image based on alpine
  images/Dockerfile
Labels: approved, lgtm, size/XS

#318 Build smaller base image in release.sh
  .ko.yaml
  hack/release.sh
Labels: approved, lgtm, size/XS

#315 Add build timeout
  pkg/apis/build/v1alpha1/build_types.go
  pkg/builder/cluster/builder.go
  pkg/builder/cluster/builder_test.go
  pkg/builder/interface.go
  pkg/builder/nop/builder.go
  pkg/controller/build/controller.go
  pkg/controller/build/controller_test.go
  pkg/webhook/build.go
  pkg/webhook/webhook_test.go
  test/build-with-timeout/build-with-high-timeout.yaml
  test/build-with-timeout/build-with-low-timeout.yaml
Labels: approved, lgtm, size/L
