Repository knative/build, pull requests merged in 2018-07, with the labels that each got.

#283 Edit knative/build readme.md
  README.md
Labels: approved, lgtm, size/L

#289 Add "godoc" and "go report" badges
  README.md
Labels: approved, lgtm, size/XS

#291 Increase goreportcard score, fix golint errors
  pkg/apis/build/register.go
  pkg/apis/build/v1alpha1/build_template_types.go
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/register.go
  pkg/builder/cluster/builder.go
  pkg/builder/cluster/convert/convert.go
  pkg/builder/common.go
  pkg/builder/google/builder.go
  pkg/builder/google/convert/convert.go
  pkg/builder/google/convert/env.go
  pkg/builder/google/convert/env_test.go
  pkg/builder/google/convert/source.go
  pkg/builder/google/convert/step.go
  pkg/builder/google/convert/step_test.go
  pkg/builder/google/convert/volume.go
  pkg/builder/google/convert/volume_test.go
  pkg/builder/google/fakecloudbuild/fake.go
  pkg/builder/interface.go
  pkg/builder/nop/builder.go
  pkg/builder/nop/builder_test.go
  pkg/builder/validation/error.go
  pkg/buildtest/data.go
  pkg/buildtest/json.go
  pkg/buildtest/wait.go
  pkg/buildtest/yaml.go
  pkg/controller/controller.go
  pkg/credentials/dockercreds/creds.go
  pkg/credentials/gitcreds/basic.go
  pkg/credentials/gitcreds/creds.go
  pkg/credentials/gitcreds/ssh.go
  pkg/credentials/initialize.go
  pkg/names.go
  pkg/webhook/build.go
  pkg/webhook/build_template.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/L

#292 Start to use `pkg/signals` from `knative/pkg`.
  Gopkg.lock
  cmd/controller/main.go
  cmd/webhook/main.go
  third_party/VENDOR-LICENSE
  vendor/github.com/knative/pkg/LICENSE
  vendor/github.com/knative/pkg/signals/signal.go
  vendor/github.com/knative/pkg/signals/signal_posix.go
  vendor/github.com/knative/pkg/signals/signal_windows.go
Labels: approved, lgtm, size/XL
