Repository knative/build, pull requests merged in 2018-12, with the labels that each got.

#486 Format markdown
  .github/issue-template.md
  .github/pull-request-template.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  code-of-conduct.md
  hack/README.md
  hack/release.md
  roadmap-2018.md
  test/README.md
  test/e2e/README.md
Labels: approved, lgtm, size/L

#489 Add dep-collector to the list of required tools in Gopkg.toml
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XS

#490 Format markdown
  DEVELOPMENT.md
  README.md
  code-of-conduct.md
  hack/README.md
  hack/release.md
  roadmap-2018.md
  test/README.md
  test/e2e/README.md
Labels: approved, lgtm, size/L

#491 Update test-infra to include latest features of release.sh
  Gopkg.lock
  hack/release.md
  hack/release.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#493 Amended docs for using docker hub with KO_DOCKER_REPO
  DEVELOPMENT.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#496 Format markdown
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#497 golang format tools
  pkg/logs/logs.go
Labels: approved, lgtm, size/XS

#508 Fix a small type in `build_test.go` : createServceAccount 😅
  pkg/reconciler/build/build_test.go
Labels: approved, lgtm, size/S
