Repository knative/build, pull requests merged in 2018-10, with the labels that each got.

#388 Remove spf13/cobra from dependencies (not used)…
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/spf13/pflag/bytes.go
  vendor/github.com/spf13/pflag/flag.go
Labels: approved, lgtm, needs-ok-to-test, size/L

#376 Controller test
  pkg/builder/nop/builder.go
  pkg/builder/nop/builder_test.go
  pkg/controller/build/controller.go
  pkg/controller/build/controller_test.go
Labels: approved, lgtm, size/L

#387 Use `/usr/bin/env bash` instead of `/bin/bash`
  hack/release.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#390 Move build-base to the build dir in GCR
  .ko.yaml
  hack/release.sh
Labels: approved, lgtm, size/S

#398 Migrate last pieces of build.dev to build.knative.dev
  pkg/builder/cluster/convert/convert_test.go
  pkg/webhook/build.go
  pkg/webhook/webhook_test.go
Labels: approved, lgtm, size/S

#385 List metadata.creationTimestamp in columns.txt
  test/columns.txt
Labels: approved, lgtm, size/XS

#401 Bump apiVersion to apps/v1 for Deployments
  config/controller.yaml
  config/webhook.yaml
Labels: approved, lgtm, size/S

#402 Add e2e test for invalid builds
  test/e2e/invalid_test.go
Labels: approved, lgtm, size/M

#337 Emit metric to track null build latency
  test/e2e-tests.sh
  test/e2e/simple_test.go
Labels: approved, lgtm, size/S

#403 Update issue and PR templates
  .github/issue-template.md
  .github/pull-request-template.md
Labels: approved, lgtm, size/M

#288 DEVELOPMENT: instructions for a local registry option
  DEVELOPMENT.md
Labels: approved, lgtm, size/S

#406 Fix TestBuildNotFoundFlow race condition
  pkg/controller/build/controller_test.go
Labels: approved, lgtm, size/S

#407 illustrate how to run go tests locally
  test/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#409 Use system.Namespace convention for holding namespace name
  cmd/webhook/main.go
  pkg/names.go
Labels: approved, lgtm, size/S

#410 Bump k8s dep to 1.11.3 and mergo to 0.3.6
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/imdario/mergo/testdata/license.yml
  vendor/github.com/knative/pkg/configmap/informed_watcher.go
  vendor/github.com/knative/pkg/kmeta/labels.go
  vendor/k8s.io/api/admission/v1beta1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1alpha1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta2/generated.pb.go
  vendor/k8s.io/api/authentication/v1/generated.pb.go
  vendor/k8s.io/api/authentication/v1beta1/generated.pb.go
  vendor/k8s.io/api/authorization/v1/generated.pb.go
  vendor/k8s.io/api/authorization/v1beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/types.go
  vendor/k8s.io/api/autoscaling/v2beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/autoscaling/v2beta1/zz_generated.deepcopy.go
  vendor/k8s.io/api/batch/v1/generated.pb.go
  vendor/k8s.io/api/batch/v1beta1/generated.pb.go
  vendor/k8s.io/api/batch/v2alpha1/generated.pb.go
  vendor/k8s.io/api/certificates/v1beta1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/events/v1beta1/generated.pb.go
  vendor/k8s.io/api/extensions/v1beta1/generated.pb.go
  vendor/k8s.io/api/networking/v1/generated.pb.go
  vendor/k8s.io/api/rbac/v1/generated.pb.go
  vendor/k8s.io/api/rbac/v1alpha1/generated.pb.go
  vendor/k8s.io/api/rbac/v1beta1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1alpha1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1beta1/generated.pb.go
  vendor/k8s.io/api/settings/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1/generated.pb.go
  vendor/k8s.io/api/storage/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/api/resource/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/labels/selector.go
  vendor/k8s.io/apimachinery/pkg/runtime/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/runtime/schema/generated.pb.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
  vendor/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/code-generator/Godeps/Godeps.json
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/protobuf/namer.go
Labels: approved, lgtm, size/XXL

#413 Fix flag name
  cmd/logs/main.go
Labels: approved, lgtm, size/XS

#415 Extract the ApplyReplacements logic from ApplyTemplate.
  pkg/builder/common.go
  pkg/builder/common_test.go
Labels: approved, lgtm, size/L

#416 Update test infrastructure for the 0.1 build release
  DEVELOPMENT.md
  hack/release.sh
  test/OWNERS
  test/columns.txt
  test/configmap/build.yaml
  test/configmap/configmap.yaml
  test/custom-env/test.yaml
  test/custom-source/0-template.yaml
  test/custom-source/1-template.yaml
  test/custom-volume/test.yaml
  test/docker-basic/0-secret.yaml
  test/docker-basic/1-serviceaccount.yaml
  test/docker-basic/2-build.yaml
  test/e2e-tests.sh
  test/fail/test.yaml
  test/gcs-archive/0-template.yaml
  test/gcs-archive/1-build.yaml
  test/git-source/0-template.yaml
  test/git-source/1-branch.yaml
  test/git-source/1-ref.yaml
  test/git-source/1-tag.yaml
  test/git-ssh/0-secret.yaml
  test/git-ssh/1-serviceaccount.yaml
  test/git-ssh/2-build.yaml
  test/git-volume/test.yaml
  test/home-volume/test.yaml
  test/home/test.yaml
  test/library.sh
  test/panic/main.go
  test/panic/test.yaml
  test/presubmit-tests.sh
  test/secret-env/build.yaml
  test/secret-env/secret.yaml
  test/secret-volume/build.yaml
  test/secret-volume/secret.yaml
  test/serviceaccount/0-serviceaccount.yaml.yaml
  test/serviceaccount/1-build.yaml
  test/serviceaccount/secret.yaml
  test/step-status/build.yaml
  test/template-args/0-template.yaml
  test/template-args/1-build.yaml
  test/template-env-merge/0-template.yaml
  test/template-env-merge/build.yaml
  test/template-volume/0-template.yaml
  test/template-volume/1-build.yaml
  test/unnamed-steps/test.yaml
  test/workingdir/main.go
  test/workingdir/test.yaml
  test/workspace/test.yaml
  tests/git-ssh/0-secret.yaml
  tests/git-ssh/id_rsa
  tests/git-ssh/id_rsa.pub
Labels: approved, lgtm, size/L

#418 Add tests for credentials package
  pkg/credentials/gitcreds/creds.go
  pkg/credentials/gitcreds/creds_test.go
Labels: approved, lgtm, size/M

#421 Use downward API instead of hard-coding build namespace
  config/controller.yaml
  config/webhook.yaml
  pkg/system/names.go
Labels: approved, lgtm, size/S

#426 Fix emitting E2E metrics
  Gopkg.lock
  test/e2e-tests.sh
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#425 Use gcr.io/distroless/base for the build-base image
  WORKSPACE
  hack/release.sh
  images/BUILD
  images/Dockerfile
Labels: approved, lgtm, size/L

#430 Fix e2e:TestInvalidBuild flakiness
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#431 use helper from test-infra in e2e test script
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#435 Revert "Use gcr.io/distroless/base for the build-base image (#425)"
  WORKSPACE
  hack/release.sh
  images/BUILD
  images/Dockerfile
Labels: approved, lgtm, size/L

#439 Fix confusing wording
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#440 include licenses in all published containers
  cmd/logs/kodata/LICENSE
  cmd/logs/kodata/VENDOR-LICENSE
  cmd/nop/kodata/LICENSE
  cmd/nop/kodata/VENDOR-LICENSE
  test/panic/kodata/LICENSE
  test/panic/kodata/VENDOR-LICENSE
  test/workingdir/kodata/LICENSE
  test/workingdir/kodata/VENDOR-LICENSE
Labels: approved, lgtm, size/XS

#444 Update to knative/pkg HEAD.
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/build/build.go
  pkg/reconciler/buildtemplate/buildtemplate.go
  pkg/reconciler/clusterbuildtemplate/clusterbuildtemplate.go
  pkg/reconciler/stats.go
  third_party/VENDOR-LICENSE
  vendor/github.com/gobuffalo/envy/LICENSE.txt
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/version.go
  vendor/github.com/joho/godotenv/LICENCE
  vendor/github.com/joho/godotenv/godotenv.go
  vendor/github.com/knative/pkg/configmap/filter.go
  vendor/github.com/knative/pkg/configmap/store.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/controller/stats_reporter.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/logging/logging.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/webhook/webhook.go
  vendor/github.com/markbates/inflect/LICENCE
  vendor/github.com/markbates/inflect/helpers.go
  vendor/github.com/markbates/inflect/inflect.go
  vendor/github.com/markbates/inflect/name.go
  vendor/github.com/markbates/inflect/version.go
Labels: approved, lgtm, size/XXL

#445 Drop methods no longer needed by webhook.
  pkg/apis/build/v1alpha1/build_template_types.go
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/cluster_build_template_types.go
Labels: approved, lgtm, size/M

#441 Ensure VENDOR-LICENSE, Gopkg.lock, and vendor have no diffs as part of verification
  hack/verify-codegen.sh
Labels: approved, lgtm, size/S

#443 Use fully-qualified name to avoid conflict w/Openshift Builds
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-yaml-tests.sh
Labels: approved, lgtm, size/S

#446 Migrate to reconciler pattern for Build
  Gopkg.lock
  cmd/controller/main.go
  pkg/controller/build/controller.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/build/template_common.go
  pkg/reconciler/build/validate_build.go
  pkg/reconciler/build/validation_test.go
  third_party/VENDOR-LICENSE
  vendor/github.com/golang/groupcache/LICENSE
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/k8s.io/client-go/tools/record/doc.go
  vendor/k8s.io/client-go/tools/record/event.go
  vendor/k8s.io/client-go/tools/record/events_cache.go
  vendor/k8s.io/client-go/tools/record/fake.go
Labels: approved, lgtm, size/XXL

#448 Automate the creation of versioned releases
  hack/README.md
  hack/release.md
  hack/release.sh
Labels: approved, lgtm, size/M

#449 [RELEASE-0.2] Pull in updates to release automation
  hack/README.md
  hack/release.md
  hack/release.sh
Labels: approved, lgtm, size/M
