Repository knative/build, pull requests merged in 2018-09, with the labels that each got.

#322 Add pod start time
  Gopkg.lock
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/builder/cluster/builder.go
  pkg/builder/cluster/builder_test.go
  pkg/builder/interface.go
  pkg/builder/nop/builder.go
  pkg/builder/nop/builder_test.go
  pkg/controller/build/controller_test.go
  test/bad-nodeselector/build-with-bad-selector.yaml
  test/columns.txt
Labels: approved, lgtm, size/L

#328 Use pkg/logging
  Gopkg.lock
  Gopkg.toml
  cmd/controller/main.go
  cmd/creds-init/main.go
  cmd/git-init/main.go
  cmd/webhook/main.go
  config/controller.yaml
  pkg/controller/build/controller.go
  pkg/controller/buildtemplate/controller.go
  pkg/controller/clusterbuildtemplate/controller.go
  pkg/logging/config.go
  pkg/webhook/build.go
  pkg/webhook/build_template.go
  pkg/webhook/certs.go
  pkg/webhook/cluster_build_template.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
  vendor/github.com/knative/pkg/configmap/default.go
  vendor/github.com/knative/pkg/configmap/doc.go
  vendor/github.com/knative/pkg/configmap/fixed.go
  vendor/github.com/knative/pkg/configmap/load.go
  vendor/github.com/knative/pkg/configmap/watcher.go
  vendor/github.com/knative/pkg/logging/config.go
  vendor/github.com/knative/pkg/logging/logger.go
  vendor/github.com/knative/pkg/logging/logkey/constants.go
  vendor/github.com/knative/pkg/logging/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#334 Address review comments from #329
  test/e2e-tests.sh
  test/e2e/README.md
  test/e2e/simple_test.go
Labels: approved, lgtm, size/M

#336 Wrap YAML E2E tests in a function
  test/e2e-tests.sh
Labels: approved, lgtm, size/M

#335 Update build execution time
  pkg/apis/build/v1alpha1/build_types.go
  pkg/builder/interface.go
  pkg/controller/build/controller.go
  pkg/controller/build/controller_test.go
  pkg/webhook/build.go
  test/bad-nodeselector/build-with-bad-selector.yaml
  test/build-with-timeout/build-with-high-timeout.yaml
  test/build-with-timeout/build-with-low-timeout.yaml
  test/e2e/e2e.go
  test/e2e/simple_test.go
Labels: approved, lgtm, size/L

#346 Test cleanup
  test/build-with-timeout/build-with-high-timeout.yaml
  test/build-with-timeout/build-with-low-timeout.yaml
  test/e2e/simple_test.go
Labels: approved, lgtm, size/S

#344 Add Pod affinity to builds
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/builder/cluster/convert/convert.go
  test/e2e/e2e.go
  test/e2e/simple_test.go
Labels: approved, lgtm, size/M

#343 use base64 -w0 instead of some random high number
  test/docker-basic/0-secret.yaml
  test/git-ssh/0-secret.yaml
Labels: approved, lgtm, size/XS

#331 Useless check err
  .gitignore
  pkg/controller/build/controller.go
Labels: approved, lgtm, size/M

#347 Add skeleton reconcilers for the core resources.
  Gopkg.lock
  cmd/controller/main.go
  pkg/controller/buildtemplate/controller.go
  pkg/controller/clusterbuildtemplate/controller.go
  pkg/reconciler/build/build.go
  pkg/reconciler/buildtemplate/buildtemplate.go
  pkg/reconciler/clusterbuildtemplate/clusterbuildtemplate.go
  vendor/github.com/knative/pkg/controller/controller.go
Labels: approved, lgtm, size/XXL

#351 Make an Errorf be Fatalf instead.
  test/e2e/simple_test.go
Labels: approved, lgtm, size/XS

#340 Trim StepStates for implicit steps
  pkg/builder/cluster/builder.go
  pkg/builder/cluster/builder_test.go
  pkg/builder/cluster/convert/convert_test.go
  pkg/builder/interface.go
  pkg/builder/nop/builder.go
  pkg/builder/nop/builder_test.go
  pkg/buildtest/diff.go
  pkg/controller/build/controller.go
Labels: approved, lgtm, size/L

#353 Have the BuildTemplate controller instantiate Image resources.
  Gopkg.lock
  cmd/controller/main.go
  config/200-clusterrole.yaml
  pkg/reconciler/buildtemplate/buildtemplate.go
  third_party/VENDOR-LICENSE
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
Labels: approved, lgtm, size/L

#356 Fixes and updates for the e2e tests
  Gopkg.lock
  test/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/L

#358 Update knative/pkg to get kmeta changes
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/buildtemplate/resources/imagecache.go
  vendor/github.com/knative/pkg/kmeta/owner_references.go
  vendor/github.com/knative/test-infra/CONTRIBUTING.md
  vendor/github.com/knative/test-infra/LICENSE
  vendor/github.com/knative/test-infra/OWNERS
  vendor/github.com/knative/test-infra/README.md
  vendor/github.com/knative/test-infra/WORKSPACE
  vendor/github.com/knative/test-infra/ci/README.md
  vendor/github.com/knative/test-infra/ci/gubernator/README.md
  vendor/github.com/knative/test-infra/ci/gubernator/config.yaml
  vendor/github.com/knative/test-infra/ci/prow/Makefile
  vendor/github.com/knative/test-infra/ci/prow/README.md
  vendor/github.com/knative/test-infra/ci/prow/boskos/README.md
  vendor/github.com/knative/test-infra/ci/prow/boskos/config.yaml
  vendor/github.com/knative/test-infra/ci/prow/boskos/config_start.yaml
  vendor/github.com/knative/test-infra/ci/prow/boskos/resources.yaml
  vendor/github.com/knative/test-infra/ci/prow/cluster.yaml
  vendor/github.com/knative/test-infra/ci/prow/config.yaml
  vendor/github.com/knative/test-infra/ci/prow/config_start.yaml
  vendor/github.com/knative/test-infra/ci/prow/plugins.yaml
  vendor/github.com/knative/test-infra/ci/prow/prow_setup.md
  vendor/github.com/knative/test-infra/ci/testgrid/Makefile
  vendor/github.com/knative/test-infra/ci/testgrid/README.md
  vendor/github.com/knative/test-infra/ci/testgrid/config.yaml
  vendor/github.com/knative/test-infra/dummy.go
  vendor/github.com/knative/test-infra/images/README.md
  vendor/github.com/knative/test-infra/images/apicoverage/Dockerfile
  vendor/github.com/knative/test-infra/images/apicoverage/Makefile
  vendor/github.com/knative/test-infra/images/apicoverage/README.md
  vendor/github.com/knative/test-infra/images/prow-tests/Dockerfile
  vendor/github.com/knative/test-infra/images/prow-tests/Makefile
  vendor/github.com/knative/test-infra/images/prow-tests/README.md
  vendor/github.com/knative/test-infra/test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/tools/README.md
  vendor/github.com/knative/test-infra/tools/apicoverage/README.md
  vendor/github.com/knative/test-infra/tools/apicoverage/apicoverage.go
  vendor/github.com/knative/test-infra/tools/apicoverage/gcs.go
  vendor/github.com/knative/test-infra/tools/apicoverage/testgrid.go
  vendor/github.com/knative/test-infra/tools/githubhelper/Makefile
  vendor/github.com/knative/test-infra/tools/githubhelper/README.md
  vendor/github.com/knative/test-infra/tools/githubhelper/githubhelper.go
Labels: approved, lgtm, size/XXL

#360 Test refactor
  test/e2e/e2e.go
  test/e2e/simple_test.go
Labels: approved, lgtm, size/L

#361 Switch from diffmatchpatch to cmp.Diff for consistency.
  Gopkg.lock
  pkg/builder/cluster/builder_test.go
  pkg/builder/cluster/convert/convert_test.go
  pkg/buildtest/diff.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go17.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go18.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/sergi/go-diff/AUTHORS
  vendor/github.com/sergi/go-diff/CONTRIBUTORS
  vendor/github.com/sergi/go-diff/LICENSE
  vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/diffmatchpatch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/match.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/mathutil.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/stringutil.go
Labels: approved, lgtm, size/XXL

#363 Release 0.1.2
  .ko.yaml
  hack/release.sh
  images/Dockerfile
Labels: approved, lgtm, size/S

#362 Start to use the common condition infrastructure from knative/pkg.
  Gopkg.lock
  Gopkg.toml
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/build_types_test.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/builder/cluster/builder.go
  pkg/builder/cluster/builder_test.go
  pkg/builder/nop/builder.go
  pkg/controller/build/controller.go
  test/e2e-tests.sh
  third_party/VENDOR-LICENSE
  vendor/github.com/knative/pkg/apis/duck/doc.go
  vendor/github.com/knative/pkg/apis/duck/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/doc.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/targettable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/duck/verify.go
  vendor/github.com/knative/pkg/apis/field_error.go
Labels: approved, lgtm, size/XXL

#365 Use k8s Duration instead of string for build timeout
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/builder/interface.go
  pkg/controller/build/controller.go
  pkg/controller/build/controller_test.go
  pkg/webhook/build.go
  pkg/webhook/webhook_test.go
  test/e2e/simple_test.go
Labels: approved, lgtm, size/M

#366 Use errgroup
  cmd/controller/main.go
Labels: approved, lgtm, size/S

#367 Add test for build types
  pkg/apis/build/v1alpha1/build_template_types_test.go
  pkg/apis/build/v1alpha1/build_types_test.go
  pkg/apis/build/v1alpha1/cluster_build_template_types_test.go
  pkg/apis/build/v1alpha1/register_test.go
Labels: approved, lgtm, size/L

#370 Update knative/pkg dep to the version serving uses
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/targettable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#371 Use custom nop image instead of busybox
  cmd/nop/main.go
  config/999-cache.yaml
  config/controller.yaml
  pkg/builder/cluster/convert/convert.go
  pkg/builder/cluster/convert/convert_test.go
Labels: approved, lgtm, size/M

#368 Add shashwathi as approver
  OWNERS
Labels: approved, lgtm, size/XS

#374 Fix columns.txt TYPE column
  test/columns.txt
Labels: approved, lgtm, size/XS

#375 Move the use of `VerifyType` in tests
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/build_types_test.go
Labels: approved, lgtm, size/XS

#377 Update pkg
  Gopkg.toml
  vendor/github.com/knative/pkg/apis/duck/unstructured.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/sinkable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/apis/interfaces.go
  vendor/github.com/knative/pkg/apis/kind2resource.go
Labels: approved, lgtm, size/XL
