Repository knative/build, pull requests merged in 2019-04, with the labels that each got.

#589 Format markdown
  README.md
Labels: approved, lgtm, size/XS

#585 Exit tailing logs for failed builds
  pkg/logs/logs.go
Labels: approved, lgtm, size/S

#584 point to new ko repo
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#592 Update dep for test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#593 Fix typos
  pkg/credentials/gitcreds/ssh.go
  pkg/logs/logs.go
  pkg/reconciler/build/resources/pod.go
  roadmap-2018.md
  test/e2e/README.md
Labels: approved, lgtm, size/S

#595 Add timeout to kubectl delete to avoid later failures
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#597 update test-infra: allow handling stock out with retries
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, lgtm, size/M
