Repository knative/build, pull requests merged in 2019-01, with the labels that each got.

#517 bump knative/caching
  Gopkg.lock
  hack/update-deps.sh
  vendor/github.com/knative/caching/Gopkg.lock
  vendor/github.com/knative/caching/OWNERS
  vendor/github.com/knative/caching/config/image.yaml
  vendor/github.com/knative/caching/hack/OWNERS
  vendor/github.com/knative/caching/hack/boilerplate/add-boilerplate.sh
  vendor/github.com/knative/caching/hack/boilerplate/boilerplate.sh.txt
  vendor/github.com/knative/caching/hack/update-codegen.sh
  vendor/github.com/knative/caching/hack/update-deps.sh
  vendor/github.com/knative/caching/hack/verify-codegen.sh
  vendor/github.com/knative/caching/pkg/apis/caching/v1alpha1/image_types.go
  vendor/github.com/knative/caching/pkg/apis/caching/v1alpha1/image_validation.go
  vendor/github.com/knative/caching/pkg/apis/caching/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/caching/test/presubmit-tests.sh
  vendor/k8s.io/code-generator/Godeps/OWNERS
  vendor/k8s.io/code-generator/OWNERS
  vendor/k8s.io/code-generator/cmd/client-gen/OWNERS
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/OWNERS
Labels: approved, lgtm, size/L

#516 Enable the status subresource
  config/200-clusterrole.yaml
  config/300-build.yaml
  config/300-buildtemplate.yaml
  config/300-clusterbuildtemplate.yaml
  pkg/apis/build/v1alpha1/build_template_types.go
  pkg/apis/build/v1alpha1/build_template_types_test.go
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/build_types_test.go
  pkg/apis/build/v1alpha1/cluster_build_template_types_test.go
  pkg/client/clientset/versioned/typed/build/v1alpha1/build.go
  pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_build.go
  pkg/reconciler/build/build.go
Labels: approved, lgtm, size/L

#495 fix (build_validation) Incorrect field paths returned
  Gopkg.lock
  Gopkg.toml
  pkg/apis/build/v1alpha1/build_template_validation.go
  pkg/apis/build/v1alpha1/build_validation.go
  pkg/apis/build/v1alpha1/build_validation_test.go
  pkg/apis/build/v1alpha1/target_path_validation.go
  pkg/apis/build/v1alpha1/target_path_validation_test.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/retired_targetable_types.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/controller/stats_reporter.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/XL

#529 Align release filename with serving repo.
  hack/release.sh
Labels: approved, lgtm, size/XS

#519 update build with a dummy status first to avoid race condition of another watch event while the pod is being created
  pkg/reconciler/build/build.go
  pkg/reconciler/build/resources/pod.go
Labels: approved, lgtm, size/M

#532 golang format tools
  pkg/reconciler/build/resources/pod.go
Labels: approved, lgtm, size/XS

#531 Use the default build/unit/integration test runners
  Gopkg.lock
  test/README.md
  test/e2e-common.sh
  test/e2e-tests-yaml.sh
  test/e2e-tests.sh
  test/e2e/e2e.go
  test/e2e/invalid_test.go
  test/e2e/randstring.go
  test/e2e/simple_test.go
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/tools/dep-collector/README.md
Labels: approved, lgtm, size/XL

#535 test/e2e: add additional checks on errors…
  test/e2e/simple_test.go
Labels: approved, lgtm, size/XS

#510 Add possibility for a client to cancel a build…
  Gopkg.lock
  pkg/apis/build/v1alpha1/build_types.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  test/e2e/cancelled_test.go
Labels: approved, lgtm, size/L

#528 Allow PersistentVolumeClaims to be parameterized
  pkg/reconciler/build/apply.go
  pkg/reconciler/build/apply_test.go
Labels: approved, lgtm, size/S

#540 Bump knative/pkg to recent version
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/apis/duck/verify.go
  vendor/github.com/knative/pkg/kmp/diff.go
  vendor/github.com/knative/pkg/kmp/doc.go
  vendor/github.com/knative/pkg/test/cleanup.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/webhook/certs.go
Labels: approved, lgtm, size/L

#536 creds-init: add support for kubernetes.io/dockerconfigjson
  pkg/credentials/dockercreds/creds.go
  pkg/credentials/dockercreds/creds_test.go
Labels: approved, lgtm, size/L

#545 creds-init: add support for `kubernetes.io/dockercfg` too
  pkg/credentials/dockercreds/creds.go
  pkg/credentials/dockercreds/creds_test.go
Labels: approved, lgtm, size/M
