Repository knative/build, pull requests merged in 2019-03, with the labels that each got.

#572 Set memory limits
  config/controller.yaml
  config/webhook.yaml
Labels: approved, lgtm, size/XS

#576 Fix broken build and overview documentation links.
  README.md
Labels: approved, lgtm, size/S

#559 Propagate the labels form the build on the pod
  pkg/reconciler/build/resources/pod.go
Labels: approved, lgtm, size/S

#587 Add support for git commit sha
  cmd/git-init/main.go
  test/e2e/e2e.go
  test/git-source/1-commitid.yaml
Labels: approved, lgtm, size/M

#586 Update links to docs repo
  README.md
  test/README.md
Labels: approved, lgtm, size/XS

#588 Add a label knative.dev/crd-install to CRDs to allow installing CRDs in a separate pass.
  config/300-build.yaml
  config/300-buildtemplate.yaml
  config/300-clusterbuildtemplate.yaml
Labels: approved, lgtm, size/XS
