Repository knative/build, pull requests merged in 2019-05, with the labels that each got.

#602 Change the name to signify that this is not handled like a normal go error
  pkg/reconciler/build/build.go
Labels: approved, lgtm, size/S

#603 Update test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#604 Bind webhook controller to a non priviliged port
  cmd/webhook/main.go
  config/400-webhook-service.yaml
Labels: approved, lgtm, size/XS

#607 Update test-infra: handle stockout to work with new error string
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#608 Update test-infra: get rid of Unbound variable running update-deps wa…
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#609 Update OWNERS to use OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, lgtm, size/M

#612 Remove unnecessary build-reviewers
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
