Repository knative/build, pull requests merged in 2019-02, with the labels that each got.

#550 Allow templating for Volumes of type secret
  pkg/reconciler/build/apply.go
  pkg/reconciler/build/apply_test.go
  test/e2e/simple_test.go
Labels: approved, lgtm, size/M

#548 Test-Infra dependency upgrade
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
  vendor/github.com/knative/test-infra/scripts/markdown-lint-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#552 replace map[string]x with string set
  Gopkg.lock
  pkg/apis/build/v1alpha1/build_template_validation.go
  pkg/reconciler/build/apply.go
  pkg/reconciler/build/resources/pod.go
  pkg/reconciler/build/validate_build.go
  pkg/reconciler/buildtemplate/resources/imagecache.go
Labels: approved, lgtm, size/M

#553 Fix release script
  Gopkg.lock
  hack/release.sh
  test/e2e-tests-yaml.sh
  test/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
Labels: approved, lgtm, size/M

#554 Updating test-infra dependency
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/M

#557 golang format tools
  pkg/reconciler/clusterbuildtemplate/resources/imagecache.go
  pkg/reconciler/clusterbuildtemplate/resources/imagecache_test.go
Labels: approved, lgtm, size/XS

#558 Bump knative/pkg - we drop webhook logic that increments spec.generation
  Gopkg.lock
  Gopkg.toml
  third_party/VENDOR-LICENSE
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/interfaces.go
  vendor/github.com/knative/pkg/webhook/webhook.go
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: approved, lgtm, size/XL

#560 Fix e2e with Go 1.12
  test/e2e/simple_test.go
Labels: approved, lgtm, size/XS

#562 Don't generate dummy pod name
  pkg/reconciler/build/build.go
  pkg/reconciler/build/resources/pod.go
  pkg/reconciler/build/resources/pod_test.go
  pkg/reconciler/build/validation_test.go
  test/e2e/simple_test.go
Labels: approved, lgtm, size/L

#563 Enforce timeouts outside of resyncs
  cmd/controller/main.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/build/timeout_handler.go
Labels: approved, lgtm, size/L

#564 update dep for github.com/knative/test-infra along with fixes
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/M

#567 Fix typo in .ko.yaml.release
  .ko.yaml.release
Labels: approved, lgtm, size/XS

#568 Rebase release-0.4 to pick up release fix
  .ko.yaml.release
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/M

#570 Update test-infra
  Gopkg.lock
  test/e2e-common.sh
  test/e2e-tests-yaml.sh
  test/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#571 Update test-infra, use its function for pod logs
  Gopkg.lock
  test/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/M
